### ISSUE TITLE
Is there a way to speed up the process?

### ISSUE THREAD

**Issue by shibaritoken** [routineLife1/AFI-ForwardDeduplicate#10]
I have rtx 4070 super and 2 frames per second don't really suit me, in the same flowframes I have under 40 fps. Is there any way to speed it up, or is it fundamentally different and this is the maximum speed for me?

**Comment by routineLife1** [comment]
In Flowframes, RIFE is used as the frame interpolation algorithm, and it operates very quickly. When you use RIFE in AFI-ForwardDeduplicate, it will also be significantly faster. If you want to increase the speed while using GMFSS, you'll need to find ways to enhance the speed of GMFSS itself. AFI-Forward is merely a computational logic and, theoretically, has already been optimized to the fullest extent.

**Comment by shibaritoken** [comment]
> In Flowframes, RIFE is used as the frame interpolation algorithm, and it operates very quickly. When you use RIFE in AFI-ForwardDeduplicate, it will also be significantly faster. If you want to increase the speed while using GMFSS, you'll need to find ways to enhance the speed of GMFSS itself. AFI-Forward is merely a computational logic and, theoretically, has already been optimized to the fullest extent.

Do you have any such ways?

**Comment by routineLife1** [comment]
Optimizing the speed of GMFSS is indeed very challenging. We have tried various methods, but none have shown significant improvements in speed.
