### ISSUE TITLE
n_forward alternative suggestion

### ISSUE THREAD

**Issue by 2994dd42d75b0** [routineLife1/AFI-ForwardDeduplicate#9]
Anime sometimes has 8fps and 12fps in same video

n_forward 2 makes video more blurriness

scene detection can be used to auto identify duplicate frames then skip them instead of using n_forward (IDK how to do this)

I did manually removed duplicate frames from video and got less blurriness as a result

**Comment by routineLife1** [comment]
The removal of duplicate frames based on recognition cannot guarantee 100% accuracy in identifying duplicate frames. It may result in under-deletion or over-deletion. However, this method avoids the need for recognition and achieves 100% accuracy by directly leveraging the principles of anime design.

**Comment by 2994dd42d75b0** [comment]
yes but this it takes a lot of time compared to GMFSS
14hrs in afi vs 5hrs in GMFSS_Fortuna with skipping 2 frames logic

any multi gpu support?
